name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can adjust this version if needed

      - name: Install dependencies
        run: npm install # Add any build commands if needed

      - name: Build project
        run: npm run build # Add your build command here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Change this to the folder containing your index.html
          cname: your-custom-domain.com # Optional: if you have a custom domain
